Change the CentOS 7 repo to vault.centos.org
cloudberrydb/bootcamp pull request #30
Opened 2024-07-17 09:23 UTC by tuhaihe

## Change logs

The CentOS Linux 7 reached the end of life (EOL) on June 30, 2024. For the sandbox based on CentOS 7, we cannot get any update using mirrors.centos.org. So change the mirror to vault.centos.org

Now it can work well on x86_64 cpu, but cannot work on ARM and other CPUs.

## Contributor's checklist

Here are some reminders before you submit your pull request:

* Make sure that your Pull Request has a clear title and commit message. You can take the [Git commit template](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) as a reference.
* Sign the Contributor License Agreement as prompted for your first-time contribution (*One-time setup*).
* Learn the [code contribution](https://cloudberrydb.org/contribute/code) and [doc contribution](https://cloudberrydb.org/contribute/doc) guides for better collaboration.
* List your communications in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb-site/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
* Feel free to ask for other people to help review and approve.

2024-07-17 09:25 UTC, tuhaihe commented
Hi @edespino could you help review this? I tested and worked well on the cloud machine.

2024-07-18 21:26 UTC, edespino commented
@tuhaihe Although the code looks ok, I am having a difficult time testing this PR due to Vault repo and EPEL repo timeouts. I will keep trying and update a comment here when I have successfully tested this PR.

2024-07-18 21:26 UTC, edespino commented
> Hi @edespino could you help review this? I tested and worked well on the cloud machine.

@tuhaihe Although the code looks ok, I am having a difficult time testing this PR due to Vault repo and EPEL repo timeouts. I will keep trying and update a comment here when I have successfully tested this PR.

2024-07-19 01:23 UTC, edespino requested changes

2024-07-19 01:23 UTC, edespino commented on 000-cbdb-sandbox/Dockerfile.RELEASE.centos7
The Vault change looks good. However, there are still a few important changes to apply to this Dockerfile.

* Remove unnecessary packages (cmake3, gcc, gcc-c++, postgresql, postgresql-devel)
* Replace the retrieval and installation of pyhon-dependencies.txt by introducing --with-pythonsrc-ext configure option.
* Replace cloudberrydb-1.5.2.zip with cloudberrydb-1.5.4.zip (latest release).

The following git diff output contains proposed changes:

```
diff --git a/000-cbdb-sandbox/Dockerfile.RELEASE.centos7 b/000-cbdb-sandbox/Dockerfile.RELEASE.centos7
index 892ed2b..57ca312 100644
--- a/000-cbdb-sandbox/Dockerfile.RELEASE.centos7
+++ b/000-cbdb-sandbox/Dockerfile.RELEASE.centos7
@@ -33,8 +33,7 @@ RUN     sed -i \

 RUN     echo root:cbdb@123 | chpasswd \
         && yum install -y initscripts unzip which tar less net-tools util-linux-ng passwd openssh-clients openssh-server perl ed m4 sudo rsync git wget \
-        && yum install -y apr-devel bison bzip2-devel cmake3 flex gcc gcc-c++ go krb5-devel libcurl-devel libevent-devel libkadm5 libxml2-devel libyaml-devel libzstd-devel openssl-devel perl-ExtUtils-Embed readline-devel xerces-c-devel zlib-devel \
-        && yum install -y postgresql postgresql-devel \
+        && yum install -y apr-devel bison bzip2-devel flex go krb5-devel libcurl-devel libevent-devel libkadm5 libxml2-devel libyaml-devel libzstd-devel openssl-devel perl-ExtUtils-Embed readline-devel xerces-c-devel zlib-devel \
         && yum install -y scl-utils \
         && yum install -y devtoolset-10

@@ -67,20 +66,11 @@ RUN     cat /tmp/90-cbdb-sysctl.conf >> /etc/sysctl.conf \
 RUN     yum install -y python3-devel python3-pip; yum clean all

 RUN     cd /tmp/ \
-        && unzip -d /tmp /tmp/cloudberrydb-${CODEBASE_VERSION_VAR}.zip \
-        && cd /tmp/cloudberrydb-${CODEBASE_VERSION_VAR} \
-        && if [ -f python-dependencies.txt ]; then \
-              pip3 install -i ${PIP_INDEX_URL_VAR} -r python-dependencies.txt; \
-           elif [ -f readmes/python-dependencies.txt ]; then \
-              pip3 install -i ${PIP_INDEX_URL_VAR} -r readmes/python-dependencies.txt; \
-           else \
-             echo "File does not exist, skipping additional commands"; \
-             exit 2; \
-           fi
+        && unzip -d /tmp /tmp/cloudberrydb-${CODEBASE_VERSION_VAR}.zip

 RUN     cd /tmp/cloudberrydb-${CODEBASE_VERSION_VAR} \
         && source scl_source enable devtoolset-10 \
-        && ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/cloudberry-db
+        && ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/cloudberry-db --with-pythonsrc-ext

 RUN     cd /tmp/cloudberrydb-${CODEBASE_VERSION_VAR} \
         && source scl_source enable devtoolset-10 \```

2024-07-19 01:51 UTC, tuhaihe commented on 000-cbdb-sandbox/Dockerfile.RELEASE.centos7
Thanks for your review! I will update the commit later. ❤️

2024-07-19 05:43 UTC, tuhaihe commented
@edespino Please take a look again. Thanks for your comments!

2024-07-19 07:52 UTC, edespino approved these changes
+1 - I verified these new changes. Thank you.

2024-07-19 08:31 UTC, merged